export const DishesLocators = {
  detailTitle: "dish-card-title",
  detail: "dish-card",
  nutrition: "dish-nutrition",
  ingredients: "dish-ingredients",
  errorBanner: "error-banner",
  draftPanel: "dish-nutrition-draft",
  name: "dish-name",
  category: "dish-category",
  portionSize: "dish-portion-size",
  calories: "dish-calories",
  protein: "dish-protein",
  fat: "dish-fat",
  carbs: "dish-carbs",
  vegan: "dish-is_vegan",
  ingredientProduct: (index: number) => `dish-ingredient-product-${index}`,
  ingredientQuantity: (index: number) => `dish-ingredient-quantity-${index}`,
  saveButton: "dish-save",
} as const;
