export const ProductsLocators = {
  detailTitle: "product-card-title",
  detail: "product-card",
  nutrition: "product-nutrition",
  errorBanner: "error-banner",
  card: "entity-card",
  cardTitle: "entity-card-title",
  cardDelete: "entity-card-delete",
  search: "products-search",
  categoryFilter: "products-category-filter",
  sortBy: "products-sort-by",
  sortOrder: "products-sort-order",
  veganFilter: "products-flag-vegan",
  name: "product-name",
  composition: "product-composition",
  category: "product-category",
  cookingState: "product-cooking-state",
  calories: "product-calories",
  protein: "product-protein",
  fat: "product-fat",
  carbs: "product-carbs",
  vegan: "product-is_vegan",
  glutenFree: "product-is_gluten_free",
  sugarFree: "product-is_sugar_free",
  photoInput: "product-photos-input",
  saveButton: "product-save",
} as const;
